openapi: 3.0.0
info:
  title: Flight Booking API
  version: 1.0.0
  description: API for managing flight bookings
servers:
  - url: http://localhost:5000
paths:
  /flights:
    get:
      summary: Get all flights
      responses:
        '200':
          description: List of all flights
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        kode_penerbangan:
                          type: string
                        kode_pesawat:
                          type: string
                        kode_maskapai:
                          type: string
                        jumlah_tiket:
                          type: integer
                        dept_IATA:
                          type: string
                        dest_IATA:
                          type: string
                        dept_time:
                          
